version: '3.7'

services:
  admin-web:
    build:
      context: .
      dockerfile: Dockerfile.admin-web
    ports:
      - 8081:8081
    depends_on:
      - redis
      - db_mysql

  merchant-web:
    build:
      context: .
      dockerfile: Dockerfile.merchant-web
    ports:
      - 8082:8082
    depends_on:
      - redis
      - db_mysql

  openapi:
    build:
      context: .
      dockerfile: Dockerfile.openapi
    ports:
      - 8083:8083
    depends_on:
      - redis
      - db_mysql
  redis:
    image: redis
    volumes:
      - redis_data:/data

volumes:
  db_data: {}
  redis_data: {}
