version: '3.7'

services:
  admin-web:
    build:
      context: .
      dockerfile: Dockerfile.admin-web
    ports:
      - 9081:8081
    depends_on:
      - redis
      - mysql

  merchant-web:
    build:
      context: .
      dockerfile: Dockerfile.merchant-web
    ports:
      - 9082:8082
    depends_on:
      - redis
      - mysql

  openapi:
    build:
      context: .
      dockerfile: Dockerfile.openapi
    ports:
      - 9083:8083
    depends_on:
      - redis
      - mysql

  mysql:
    image: mysql:8
    ports:
      - 4306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=greenpay
      - MYSQL_USER=greenpay
      - MYSQL_PASSWORD=greenpay
      - TZ=Asia/Shanghai
    command: [
      "--default_authentication_plugin=mysql_native_password",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
    volumes:
      - mysql_data:/var/lib/mysql/data

  redis:
    image: redis
    volumes:
      - redis_data:/data

volumes:
  mysql_data: {}
  redis_data: {}
