version: '3.7'

services:
  admin_web:
    image: registry.cn-hongkong.aliyuncs.com/esiran/greenpay-admin-web
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - redis
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DB=greenpay
      - MYSQL_USER=root
      - MYSQL_PASS=greenpay
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KAFKA_BOOTSTRAP_SERVER=103.117.139.58:9092

  merchant_web:
    image: registry.cn-hongkong.aliyuncs.com/esiran/greenpay-merchant-web
    restart: always
    ports:
      - 8082:8082
    depends_on:
      - redis
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DB=greenpay
      - MYSQL_USER=root
      - MYSQL_PASS=greenpay
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  openapi:
    image: registry.cn-hongkong.aliyuncs.com/esiran/greenpay-openapi
    restart: always
    ports:
      - 8083:8083
    depends_on:
      - redis
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DB=greenpay
      - MYSQL_USER=root
      - MYSQL_PASS=greenpay
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - GRENNPAY_WEB_HOST=http://api.newpays.biz
      - KAFKA_BOOTSTRAP_SERVER=103.117.139.58:9092
  mysql:
    restart: always
    image: mysql:8
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=greenpay
      - MYSQL_DATABASE=greenpay
      - MYSQL_USER=greenpay
      - MYSQL_PASSWORD=greenpay
      - TZ=Asia/Shanghai
    command:
      --default_authentication_plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    restart: always
    image: redis
    volumes:
      - redis_data:/data

volumes:
  mysql_data: {}
  redis_data: {}
