server:
  port: 8081

logging:
  level:
    com.github.binarywang.wxpay: error
    me.chanjar.weixin: error
    com.esiran.greenpay.common.sign: debug

spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /**
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: 0
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      missing-topics-fatal: false
delay_queue:
  redis:
    default_key: 'greenpay:delay_queue'
  consumer:
    enabled: true

shiro:
  loginUrl: /login
  successUrl: /home