server:
  port: 8081

logging:
  level:
    com.github.binarywang.wxpay: error
    me.chanjar.weixin: error

spring:
  profiles:
    active: dev_home
  mvc:
    static-path-pattern: /**
delay_queue:
  redis:
    default_key: 'greenpay:delay_queue'
  consumer:
    enabled: true

shiro:
  loginUrl: /admin/login
  successUrl: /admin/home