server:
  port: 8081
#  servlet:
#    context-path: /admin
logging:
  level:
    com.github.binarywang.wxpay: error
    me.chanjar.weixin: error

spring:
  profiles:
    active: dev
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    mode: LEGACYHTML5
    cache: false
  mvc:
    static-path-pattern: /**
delay_queue:
  redis:
    default_key: 'greenpay:delay_queue'
  consumer:
    enabled: true

shiro:
  loginUrl: /login
  successUrl: /home