server:
  port: 80
logging:
  level:
    com.github.binarywang.wxpay: error
    me.chanjar.weixin: error

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.158:3306/greenpay?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: ruixiao123
  redis:
    port: 6379
    host: 192.168.3.158
    password: ruixiao123

web:
  host: http://prepaid.globalrecharge.cn

glprepaid:
  sync_default_up_val: 15
  order:
    automatic_expire: 900000
    test_amount: true

api_key:
  juhe_exchange_rate: f8d8fdaabf69892506f341e73a02b7ad

wechat:
  app_id: wx4f127069332392ff
  app_secret: caa76507ea4828bd033b9b20b20c2264
  mch_id: 1535033191
  mch_key: tr528KCf9JtIt2fNfM3E6taYupea6sF7
  cert_path: classpath:/keystory/wxpay/apiclient_cert_prod.p12

dingconnect:
  api_key: GIzE4xJ9Bj26S8CuqYYg8w
