server:
  port: 8088

logging:
  level:
    com.github.binarywang.wxpay: error
    me.chanjar.weixin: error

spring:
  profiles:
    active: dev_home
  mvc:
    static-path-pattern: /**
  thymeleaf:
    enabled: false
  redis:
    port: 6379
    host: 127.0.0.1
web:
  hostname: http://s7buy.esiran.com

delay_queue:
  redis:
    default_key: 'greenpay:delay_queue'
  consumer:
    enabled: false

wechat:
  app_id: wx2aeda339f56138bf
  app_secret: 731787f51247a33c4ff210cd613dd780
  mch_id: 1519342911
  mch_key: 2624eedd356624bc7a662c29ceb0a20e
