server:
  port: 8083

logging:
  level:
    com.github.binarywang.wxpay: error
    me.chanjar.weixin: error

spring:
  profiles:
    active: dev_home
  mvc:
    static-path-pattern: /**
  thymeleaf:
    enabled: true
  redis:
    port: 6379
    host: 127.0.0.1
web:
  hostname: http://s7buy.esiran.com

delay_queue:
  redis:
    default_key: 'greenpay:delay_queue'
  consumer:
    enabled: false